import React, { useEffect, useRef, useState } from 'react';
import MANIFEST from '../../images-manifest.json';

/**
 * Serves estate photography from the pre-generated optimised set in
 * public/images/opt/.  Each image is available as:
 *   {slug}-{w}.webp  (640 / 1280 / 1920 — whichever fit the original)
 *   {slug}-{fw}.jpg  (JPEG fallback at the largest available width ≤ 1280)
 *
 * The manifest (generated by scripts/optimize-images.js) records which widths
 * each slug actually has, so we never reference a file that doesn't exist.
 *
 * Blur-up (LQIP) strategy:
 *   1. The 640w WebP is shown immediately as a blurred background (CSS blur).
 *   2. The full-resolution <img> fades in on top once it has loaded.
 *   This gives instant visual feedback instead of a blank shimmer.
 *
 * `fit` overrides the default `object-fit: cover` (e.g. `contain` for a
 * logo mark that must not be cropped). Only meaningful for manifest entries
 * without WebP variants, since those never render the LQIP crop layer.
 */

const OPT = `${process.env.PUBLIC_URL}/images/opt`;

export default function EstateImage({
  slug,
  alt,
  className = '',
  priority = false,
  sizes = '100vw',
  fit = 'cover',
}) {
  const [loaded, setLoaded] = useState(false);
  const imgRef = useRef(null);

  useEffect(() => {
    const img = imgRef.current;
    if (!img) return;
    if (img.complete && img.naturalWidth > 0) setLoaded(true);
  }, []);

  const info = MANIFEST[slug];

  if (!info) {
    /* Slug not in manifest — fall back to original (dev / missing asset). */
    return (
      <span className={`img-placeholder ${className}`}>
        <img
          ref={imgRef}
          src={`${process.env.PUBLIC_URL}/images/${slug}.jpg`}
          alt={alt}
          loading={priority ? 'eager' : 'lazy'}
          decoding={priority ? 'sync' : 'async'}
          fetchPriority={priority ? 'high' : undefined}
          onLoad={() => setLoaded(true)}
          className={`img-zoom ${loaded ? 'img-loaded' : ''}`}
          style={{ objectFit: fit }}
        />
      </span>
    );
  }

  const { widths, fallbackWidth, src: customSrc } = info;

  /* Only WebP has multiple widths in opt/. The JPEG fallback is a single file:
     {slug}-{fallbackWidth}.jpg when fallbackWidth is set, or {slug}.jpg when
     the image was placed in opt/ directly without going through the optimiser.
     customSrc handles non-.jpg extensions (e.g. farm.jpeg). */
  const hasWebP = widths && widths.length > 0;
  const webpSrcset = hasWebP
    ? widths.map((w) => `${OPT}/${slug}-${w}.webp ${w}w`).join(', ')
    : '';
  const fallbackSrc = customSrc
    ? customSrc.startsWith('/')
      ? customSrc
      : `${process.env.PUBLIC_URL}/${customSrc}`
    : fallbackWidth != null
      ? `${OPT}/${slug}-${fallbackWidth}.jpg`
      : `${OPT}/${slug}.jpg`;

  /* Blur-up placeholder: use the smallest WebP as the blurred background.
     Only when we have WebP variants (not custom-src JPEG-only images). */
  const lqipSrc = hasWebP ? `${OPT}/${slug}-${widths[0]}.webp` : null;

  return (
    <span className={`img-placeholder ${className}`}>
      {/* Blurred low-quality placeholder — instantly visible */}
      {lqipSrc && (
        <img
          src={lqipSrc}
          aria-hidden="true"
          alt=""
          className="img-lqip"
        />
      )}
      {/* Full-resolution image — fades in once loaded */}
      <picture className="img-full">
        {hasWebP && (
          <source type="image/webp" srcSet={webpSrcset} sizes={sizes} />
        )}
        <img
          ref={imgRef}
          src={fallbackSrc}
          alt={alt}
          loading={priority ? 'eager' : 'lazy'}
          decoding={priority ? 'sync' : 'async'}
          fetchPriority={priority ? 'high' : undefined}
          onLoad={() => setLoaded(true)}
          className={`img-zoom ${loaded ? 'img-loaded' : ''}`}
          style={{ objectFit: fit }}
        />
      </picture>
    </span>
  );
}
